### ISSUE TITLE
Улучшить ридми

### ISSUE THREAD

**Issue by mysmah** [mysmah/Mira#18]
# Думаю нужно улучшить ридми
## Причины:
* Выглядит криво
* Нужно лучше описать что мы делаем для тех кто присоединятся к проекту
* Желательно убрать инфу о том что сейчас происходит, т.к. для этого есть более подходящие места
## Предложения:
* Переписать всё ридми с нуля
* Написать описание Миры
* Написать описание того что хотим получить в итоге

**Comment by PacketCat** [comment]
Нихуя не удобно, лучше в тг, в лс делать

**Comment by mysmah** [comment]
Готово
#22
