### ISSUE TITLE
Добавить все что надо для счастья комьюнити

### ISSUE THREAD

**Issue by mysmah** [mysmah/Mira#20]
# Добавить все что надо [для счастья комьюнити](https://github.com/mysmah/Mira/community)
## Причины
* Чтобы было
* Так надо (ну делают же)
* Будет возникать меньше проблем (наверное)

**Comment by mysmah** [comment]
довойте начнем с лицензии

**Comment by PacketCat** [comment]
Какие у нас лицензии? @mysmah

**Comment by PacketCat** [comment]
Кст, дай мне write access, я заебался пулы создавать

**Comment by mysmah** [comment]
@PacketCat 
Issue templates

**Comment by mysmah** [comment]
го писать

**Comment by mysmah** [comment]
хотя ненад

**Comment by mysmah** [comment]
может потом

**Comment by mysmah** [comment]
@PacketCat думою пока хватит, закроем?

**Comment by mysmah** [comment]
а пока думаю лучше зоняца распространением

**Comment by mysmah** [comment]
и улучшением бота

**Comment by mysmah** [comment]
кст может потом на катуни переведём?
