### ISSUE TITLE
Callback processing

### ISSUE THREAD

**Issue by PacketCat** [mysmah/Mira#29]
### Сделать полноценный процессинг коллбэка
* Класс коллбэк-сообщений
* Хандлинг коллбэка
* Сохранение массива коллбэк-сообщений и загрузка

**Comment by PacketCat** [comment]
@mysmah этим я сам попытаюсь заняться

**Comment by mysmah** [comment]
нахуя?

**Comment by PacketCat** [comment]
Хз, потом пригодится

**Comment by PacketCat** [comment]
@mysmah всмысоле
